# Generated by Django 3.1.6 on 2021-03-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpos', '0002_bill_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_number',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
