# Generated by Django 3.1.6 on 2021-03-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpos', '0002_addtypefood_bill_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddTypeFood',
        ),
    ]
